import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home({posts}) {

  // const [posts, setPosts] = useState([])

  // useEffect(() => {
  //   const data = fetch('https://jsonplaceholder.typicode.com/posts?_limit=8')
  //     .then(r => r.json()) // converti la réponse en json
  //     .then(setPosts) // on met à jour le state
  //     // ou
  //     // .then(data => { // quand la réponse est convertie en json
  //     //   setPosts(data) // on met à jour le state
  //     // })
  // }, []) // tableau vide pour ne pas relancer la requête à chaque render

  return (
    <>
      <Head>
        <title>NextJS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {posts.map(post =>
          <li key={post.id} className="post">
            <Link href={`/blog/${post.id}`}>
              <h3>{post.id} - {post.title}</h3>
            </Link>
          </li>
        )}
      </ul>
    </>
  )
}

export async function getStaticProps() { // permet de générer les pages statiquement
  const posts = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=8')
      .then(r => r.json())
  return {
    props: { // props est un objet qui sera passé en paramètre à la fonction Home
      posts
    }
  }
}
